### ISSUE TITLE
プラグインの説明を付ける

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey-bbpress-support#25]
This plugin is displays the bbpress forum beautifully with Snow Monkey.
「このプラグインは、Snow Monkeyでbbpressフォーラムを美しく表示します。」

とか説明どうっすかー？w

**Comment by inc2734** [comment]
「このプラグインは Snow MonkeyでbbPress を美しく表示し、いくつかの機能を追加します。」で入れます！
