### ISSUE TITLE
返信へのいいねボタンにホバーしたらいいねした人のユーザー名を表示させたい

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey-bbpress-support#62]

**Comment by kmix-39** [comment]
スマホ時にはホバーの代わりにどう表示させるか。
ボタン長押しでユーザー名表示だと誤動作で押す処理が発生しそう。

**Comment by inc2734** [comment]
長押しとか考えると js でやらないといけなくなって複雑化するから、単純に `visibility: hidden` しておいたのをホバーで `visibility: visible` にするくらいのほうが大変じゃなさそう…。

**Comment by kmix-39** [comment]
スマホやタブレットだとタッチデバイスだからホバーが難しい問題があって。
とは言え、ボタンの長押しってsubmit走ったり、ブラウザイベントが発動するデバイスも存在するし…複雑ですね。

マウスカーソルが存在するPC専用の機能で単純に考えてみますか。

**Comment by inc2734** [comment]
あーなるほど。スマホ・タブレットは考えていませんでした。たしかにそうですね…。

> マウスカーソルが存在するPC専用の機能で単純に考えてみますか。

最初はこれで良い気がします。

**Comment by kutsu123** [comment]
（お邪魔します）
たぶん、Snow Monkeyでゴニョゴニョしようか！って思う人はほぼPCだとは思うので、ひとまずPCのみで良い気がします

しかし、このボタン押した人わかる機能って、けっこう奥が深いというかこだわろうとすると色々検討することがでてきて、安易につけちゃえ〜とならないのがしみじみと。

ちなスマホだと、SlackのUIとおそろにする（懸念の長押し発火）もありますが、単純にもう最初からあまり邪魔にならない位置で名前とか表示するとかでもありかなとも思いました（画面の領域食いますが・・・）

====

[返信の本文]

この返信文にいいねした人：xxx,yyy,zzz （もっと見る）

====

みたいなのとか？？

**Comment by kmix-39** [comment]
> ちなスマホだと、SlackのUIとおそろにする（懸念の長押し発火）もありますが、単純にもう最初からあまり邪魔にならない位置で名前とか表示するとかでもありかなとも思いました（画面の領域食いますが・・・）

あー、なるほど。
単純に、ポップアップ作る前にその形のラベル表示で作っておいた方がデザイン調整やマージもしやすいですね。
この issue ってデザイン以外は重くないと思うんですがデザイン周りが奥深いんで先にロジック系だけ書けば後はCSSなり調整の繰り返しになる気もする^^;

キタジマ氏 >
週末作業になりますけど、試作的にユーザー名表示を単純なラベル表示の感じでやってみますかねー。

**Comment by inc2734** [comment]
ひとまず kmix-39 さんにプルリクいただいたものをベースにし、Backlog やはてなブックマークみたいにアバターで表示するようにしてみました。将来的には PC はホバー、スマホは普通に表示（あるいはいっそのこと非表示）という形にしようかなーと考えています。
