### ISSUE TITLE
npm run test:lintが通らない

### ISSUE THREAD

**Issue by scaltinov** [inc2734/snow-monkey-bbpress-support#83]
# 以下を解消させたあとに、

FILE: /app/snow-monkey-bbpress-support/App/Stars.php
\---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 25 ERRORS AFFECTING 23 LINES
\---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 103 | ERROR | [x] Tabs must be used to indent lines; spaces are not allowed (Generic.WhiteSpace.DisallowSpaceIndent.SpacesUsed)

〜省略〜

\---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 25 MARKED SNIFF VIOLATIONS AUTOMATICALLY
\---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Time: 3.46 secs; Memory: 18MB

# 以下が発生します

% npm run test:lint

\> @ test:lint /Applications/MAMP/htdocs/vanilla/wp-content/plugins/snow-monkey-bbpress-support
\> run-s test:lint:*

\> @ test:lint:php /Applications/MAMP/htdocs/vanilla/wp-content/plugins/snow-monkey-bbpress-support
\> wp-env start && wp-env run composer run-script lint

WordPress development site started at http://localhost:8888/
WordPress test site started at http://localhost:8889/
MySQL is listening on port 52054

 ✔ Done! (in 1s 855ms)
ℹ Starting 'run-script lint' on the composer container. 

Creating 69dd2c1b89de9fbf44038fb68574375d_composer_run ... done
\> phpcs --standard=./.phpcs.xml.dist
...................
Fatal error: Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, string given in /app/vendor/squizlabs/php_codesniffer/src/Files/File.php:1056
Stack trace:
\#0 /app/vendor/squizlabs/php_codesniffer/src/Files/File.php(1056): vsprintf('Expected exactl...', '\n')
\#1 /app/vendor/squizlabs/php_codesniffer/src/Files/File.php(672): PHP_CodeSniffer\Files\File->addMessage(true, 'Expected exactl...', 16, 12, 'ExtraSpaceAfter...', '\n', 5, true)
\#2 /app/vendor/squizlabs/php_codesniffer/src/Files/File.php(780): PHP_CodeSniffer\Files\File->addError('Expected exactl...', 61, 'ExtraSpaceAfter...', '\n', 0, true)
\#3 /app/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php(395): PHP_CodeSniffer\Files\File->addFixableError('Expected exactl...', 61, 'ExtraSpaceAfter...', \'\n')
\#4 /app/vendor/wp-coding-standards/wpcs/WordPress/Sniff.php(910): WordPressCS\WordPress\Sniffs\WhiteSpace\ControlStructureSpacingSniff->process_token(61)
\#5 /app/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): WordPressCS\WordPress\Sniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 61)
\#6 /app/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(92): PHP_CodeSniffer\Files\File->process()
\#7 /app/vendor/squizlabs/php_codesniffer/src/Runner.php(631): PHP_CodeSniffer\Files\LocalFile->process()
\#8 /app/vendor/squizlabs/php_codesniffer/src/Runner.php(434): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
\#9 /app/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
\#10 /app/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
\#11 /app/vendor/bin/phpcs(117): include('/app/vendor/squ...')
\#12 {main}
  thrown in /app/vendor/squizlabs/php_codesniffer/src/Files/File.php on line 1056
Script phpcs --standard=./.phpcs.xml.dist handling the lint event returned with error code 255
ERROR: 255
✖ Command failed with exit code 255

# 下記によると、Wordpress Coding Standardが原因のようです。
https://github.com/squizlabs/PHP_CodeSniffer/issues/3196

なので、
.phpcs.xml.dist
を修正すると直りそうです

**Comment by inc2734** [comment]
わー気づいてませんでした、すみません。修正します！
